# Generated by Django 4.2.2 on 2023-08-11 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('topic', models.CharField(blank=True, choices=[('Transfers', 'Transfers'), ('Breaking News', 'Breaking News'), ('Announcement', 'Announcement'), ('Results', 'Results'), ('Fixture', 'Fixture'), ('Other', 'Other')], max_length=200, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=300)),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
                ('to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle')),
            ],
        ),
    ]
