# Generated by Django 4.2.2 on 2023-08-11 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=300)),
                ('date_time_of_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='newssource',
            name='article',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='topic',
            field=models.CharField(blank=True, choices=[('Transfers', 'Transfers'), ('Breaking News', 'Breaking News'), ('Announcement', 'Announcement'), ('Results', 'Results'), ('Fixture', 'Fixture'), ('Other', 'Other')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
        migrations.AddField(
            model_name='comment',
            name='to_photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle'),
        ),
    ]
