# Generated by Django 4.2.2 on 2023-08-04 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='source',
        ),
        migrations.AddField(
            model_name='newscategory',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newssource',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.newsarticle'),
            preserve_default=False,
        ),
    ]
