# Generated by Django 4.2.2 on 2023-08-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_comment_remove_newssource_article_newsarticle_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='to_photo',
            new_name='to_article',
        ),
    ]
