# Generated by Django 4.2.2 on 2023-07-09 08:47

import django.core.validators
from django.db import migrations, models
import football_news_aggregator.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_team',
            field=models.CharField(default=1, max_length=30, validators=[django.core.validators.MinLengthValidator(2), football_news_aggregator.common.validators.validate_only_letters]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
